[toolchain]
channel = "stable"
components = [ "rust-src", "clippy-preview", "rustfmt-preview", "llvm-tools-preview" ]
targets = [
    "aarch64-apple-darwin",
    "aarch64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
]
