name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          diagnostic-endpoint: ""
      - name: Nix caching
        uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          diagnostic-endpoint: ""
      - name: Run Nix checks
        run: nix flake check -L
      - name: Build Codecov report
        run: |
          nix build -L .#checks.x86_64-linux.systemd-credsubst-nextest
      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          files: ./result/codecov.json
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Build static binary
        run: nix build -L .#systemd-credsubst-static
      - name: Upload static binary
        uses: actions/upload-artifact@v4
        with:
          name: systemd-credsubst
          path: ./result/bin/systemd-credsubst
          if-no-files-found: error
          retention-days: ${{ github.event_name == 'pull_request' && 5 || 0 }}

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          diagnostic-endpoint: ""
      - name: Nix caching
        uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          diagnostic-endpoint: ""
      - name: Run Nix checks
        run: nix flake check -L
